apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-ingress
  namespace: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-ingress
    spec:
      containers:
      - name: api-ingress
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.14.0
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/api-fake-default-backend-service
        - --default-ssl-certificate=api/crossroads-ssl
        - --annotations-prefix=nginx.ingress.kubernetes.io
        - --ingress-class=nginx-api
        - --watch-namespace=$(POD_NAMESPACE)