apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api
  annotations:
    ingress.kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    # nginx.ingress.kubernetes.io/add-base-url: "true" # Does not appear we need this
spec:
  tls:
  - hosts:
    - $API_HOST_NAME_TEMP
    secretName: crossroads-ssl
  rules:
  - host: $API_HOST_NAME_TEMP
    http:
      paths:
      - path: /fred
        backend:
          serviceName: fred-service
          servicePort: 80
      - path: /attendance
        backend:
          serviceName: attendance-service
          servicePort: 80
      - path: /finance
        backend:
          serviceName: crds-finance-service
          servicePort: 80