apiVersion: v1
kind: ConfigMap
metadata:
  name: crds-ingress-nginx-config
data:
  proxy-connect-timeout: "300"
  proxy-read-timeout: "300"
  proxy-send-timeout: "120"
  proxy-body-size: "10g"