apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crds-ingress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crds-ingress
    spec:
      containers:
      - name: crds-ingress
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/maestro-phoenix-service
        - --configmap=$(POD_NAMESPACE)/crds-ingress-nginx-config
        - --default-ssl-certificate=default/crossroads-ssl
        - --annotations-prefix=ingress.kubernetes.io
        - --ingress-class=nginx