apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: crds-ingress-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crds-ingress
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
