apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: crds-ingress
  annotations:
    ingress.kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - maestro-int.crossroads.net
    - contentint.crossroads.net
    - golocal-int.crossroads.net
    secretName: crossroads-ssl
  rules:
  - host: maestro-int.crossroads.net
    http:
      paths:
      - path: /
        backend:
          serviceName: maestro-varnish-service
          servicePort: 80
  - host: contentint.crossroads.net
    http:
      paths:
      - path: /api
        backend:
          serviceName: cms-varnish-service
          servicePort: 80
      - path: /
        backend:
          serviceName: cms-ss-admin
          servicePort: 80
  - host: golocal-int.crossroads.net
    http:
      paths:
      - path: /
        backend:
          serviceName: go-local-service
          servicePort: 80