apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: crds-ingress
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - $CHATTY_CATHY_HOST_NAME
    - $CMS_HOST_NAME
    - $CRDS_FORM_BUILDER_FRONTEND_HOST_NAME
    secretName: crossroads-ssl
  rules:
  - host: $CRDS_FORM_BUILDER_FRONTEND_HOST_NAME
    http:
      paths:
      - path: /
        backend:
          serviceName: crds-form-builder-frontend-service
          servicePort: 80
  - host: $CMS_HOST_NAME
    http:
      paths:
      - path: /api/contentblock
        backend:
          serviceName: redirect-service
          servicePort: 80
  - host: $CHATTY_CATHY_HOST_NAME
    http:
      paths:
      - path: /
        backend:
          serviceName: chatty-cathy-service
          servicePort: 80
