apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: crds-ingress
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - $CHATTY_CATHY_HOST_NAME
    secretName: crossroads-ssl
  - host: $CRDS_FORM_BUILDER_FRONTEND_HOST_NAME
    http:
      paths:
      - path: /
        backend:
          serviceName: crds-form-builder-frontend-service
          servicePort: 80
  - host: $CHATTY_CATHY_HOST_NAME
    http:
      paths:
      - path: /
        backend:
          serviceName: chatty-cathy-service
          servicePort: 80