apiVersion: v1
kind: ConfigMap
metadata:
  name: redirect-config
data:
  default.conf: |
    server {
      listen                  80;
      server_name             crossroads.net;
      location /media {
        rewrite ^/media(.*)$ ${MEDIA_URL}$1? permanent; # Keep query string by removing trailing '?'
      }
      
      location /series {
        return 301 ${MEDIA_URL}$uri; # Keep query string by using $request_uri instead of $uri
      }

      location /message {
        return 301 ${MEDIA_URL}$uri;
      }

      location /podcasts {
        return 301 ${MEDIA_URL}$uri;
      }
    }
    