apiVersion: v1
kind: ConfigMap
metadata:
  name: redirect-config
data:
  default.conf: |

    server {
      listen                  80;
      server_name             ${CMS_HOST_NAME};
      location / {
        proxy_pass  ${SS_CMS_WRAPPER_URL};
      }
    }

    server {
      listen                  80 default_server;
      location /health {
          return 200 'alive';
          add_header Content-Type text/plain;
      }
    }
