apiVersion: v1
kind: ConfigMap
metadata:
  name: redirect-config
data:
  default.conf: |
    server {
      listen                  80;
      server_name             crossroads.net;
      location /media {
        rewrite ^/media(.*)$ ${MEDIA_URL}$1 permanent;
      }
      
      location /series {
        return 301 {MEDIA_URL}$uri;
      }

      location /message {
        return 301 {MEDIA_URL}$uri;
      }

      location /podcasts {
        return 301 {MEDIA_URL}$uri;
      }
      # rewrite ^/series(.*)$ ${MEDIA_URL}/series$1 permanent;
      # rewrite ^/message(.*)$ ${MEDIA_URL}/message$1 permanent;
      # rewrite ^/podcasts(.*)$ ${MEDIA_URL}/podcasts$1 permanent;
    }
    